export enum EventType {

    Unknown = 'unknown',

    AccountLogin = 'accountLogin',
    AccountLogout = 'accountLogout',
    AccountRefresh = 'accountRefresh',
    AccountConfirm = 'accountConfirm',
    AccountIsEmailVerified = 'accountIsEmailVerified',
    AccountChangeEmail = 'accountChangeEmail',
    AccountChangePassword = 'accountChangePassword',
    AccountForgotToken = 'accountForgotToken',
    AccountForgotConfirm = 'accountForgotConfirm',
    AccountRevoke = 'accountRevoke',
    AccountGetTwoFactorToken = 'accountGetTwoFactorToken',
    AccountEnableTwoFactorAuthentication = 'accountEnableTwoFactorAuthentication',
    AccountDisableTwoFactorAuthentication = 'accountDisableTwoFactorAuthentication',
    
    AuthClientsCreate = 'authClientsCreate',
    AuthClientsList = 'authClientsList',
    AuthClientsRead = 'authClientsRead',
    AuthClientsUpdate = 'authClientsUpdate',
    AuthClientsDelete = 'authClientsDelete',

    AuthDynamicClientsCreate = `authDynamicClientsCreate`,
    
    OAuthAuthenticate = 'oAuthAuthenticate',
    OAuthAuthenticateCallback = 'oAuthAuthenticateCallback',
    OAuthToken = 'oAuthToken',

    RegisterNewUser = 'registerNewUser',
    RegisterUserName = 'registerUserName',
    RegisterEmail = 'registerEmail',
    
    RolesCreate = 'rolesCreate',
    RolesList = 'rolesList',
    RolesRead = 'rolesRead',
    RolesUpdate = 'rolesUpdate',
    RolesDelete = 'rolesDelete',
    
    UsersList = 'usersList',
    UsersRead = 'usersRead',
    UsersUpdate = 'usersUpdate',
    UsersDelete = 'usersDelete',
    UsersFollow = 'usersFollow',
    UsersUnfollow = 'usersUnfollow',
    UsersFollowers = 'usersFollowers',
    UsersFollowing = 'usersFollowing',
    UsersMute = 'usersMute',
    UsersUnmute = 'usersUnmute',
    UsersEnable = 'usersEnable',
    UsersDisable = 'usersDisable',
    UserRolesConnect = 'userRolesConnect',
    UserRolesDisconnect = 'userRolesDisconnect',
    UserApprove = 'userApprove',
    UserReject = 'userReject',
    UserFeature = 'userFeature',
    UserUnfeature = 'userUnfeature',
    UsersStatuses = 'usersStatuses',
    
    AvatarUpdate = 'avatarUpdate',
    AvatarDelete = 'avatarDelete',

    HeaderUpdate = 'headerUpdate',
    HeaderDelete = 'headerDelete',
    
    AttachmentsCreate = 'attachmentsCreate',
    AttachmentsUpdate = 'attachmentsUpdate',
    AttachmentsDelete = 'attachmentsDelete',
    AttachmentsDescribe = 'attachmentsDescribe',
    AttachmentsHashtags = 'attachmentsHashtags',
    
    SettingsList = 'settingsList',
    SettingsPublic = 'settingsPublic',
    SettingsUpdate = 'settingsUpdate',
    
    ActivityPubRead = 'activityPubRead',
    ActivityPubInbox = 'activityPubInbox',
    ActivityPubOutbox = 'activityPubOutbox',
    ActivityPubFollowing = 'activityPubFollowing',
    ActivityPubFollowers = 'activityPubFollowers',
    ActivityPubLiked = 'activityPubLiked',
    ActivityPubSharedInbox = 'activityPubSharedInbox',
    ActivityPubStatus = 'activityPubStatus',
    
    Webfinger = 'webfinger',
    Nodeinfo = 'nodeinfo',
    HostMeta = 'hostMeta',
    Instance = 'instance',
    
    CountriesList = 'countriesList',
    LocationsList = 'locationsList',
    LocationsRead = 'locationsRead',

    CategoriesList = 'categoriesList',
    
    StatusesList = 'statusesList',
    StatusesCreate = 'statusesCreate',
    StatusesRead = 'statusesRead',
    StatusesUpdate = 'statusesUpdate',
    StatusesDelete = 'statusesDelete',
    StatusesUnlist = 'statusesUnlist',
    StatusesReblog = 'statusesReblog',
    StatusesUnreblog = 'statusesUnreblog',
    StatusesFavourite = 'statusesFavourite',
    StatusesUnfavourite = 'statusesUnfavourite',
    StatusesBookmark = 'statusesBookmark',
    StatusesUnbookmark = 'statusesUnbookmark',
    StatusesFeature = 'statusesFeature',
    StatusesUnfeature = 'statusesUnfeature',
    StatusesContext = 'statusesContext',
    StatusesReblogged = 'statusesReblogged',
    StatusesFavourited = 'statusesFavourited',
    
    TimelinesPublic = 'timelinesPublic',
    TimelinesCategories = 'timelinesCategories',
    TimelinesHashtags = 'timelinesHashtags',
    TimelinesFeatured = 'timelinesFeaturedStatuses',
    TimelinesFeaturedUsers = 'timelinesFeaturedUsers',
    TimelinesHome = 'timelinesHome',
    
    FollowRequestList = 'followRequestList',
    FollowRequestApprove = 'followRequestApprove',
    FollowRequestReject = 'followRequestReject',
    
    NotificationsList = 'notificationsList',
    NotificationsCount = 'notificationsCount',
    NotificationsUpdateMarker = 'notificationsUpdateMarker',

    Relationships = 'relationships',
    Search = 'search',

    InvitationList = 'invitationList',
    InvitationGenerate = 'invitationGenerate',
    InvitationDelete = 'invitationDelete',

    ReportsCreate = 'reportsCreate',
    ReportsList = 'reportsList',
    ReportsClose = 'reportsClose',
    ReportsRestore = 'reportsRestore',

    TrendingStatuses = 'trendingStatuses',
    TrendingUsers = 'trendingUsers',
    TrendingHashtags = 'trendingHashtags',

    BookmarksList = 'bookmarksList',
    FavouritesList = 'favouritesList',

    InstanceBlockedDomainsList = 'instanceBlockedDomainsList',
    InstanceBlockedDomainsCreate = 'instanceBlockedDomainsCreate',
    InstanceBlockedDomainsUpdate = 'instanceBlockedDomainsUpdate',
    InstanceBlockedDomainsDelete = 'instanceBlockedDomainsDelete',

    PushSubscriptionsList = 'pushSubscriptionsList',
    PushSubscriptionsCreate = 'pushSubscriptionsCreate',
    PushSubscriptionsUpdate = 'pushSubscriptionsUpdate',
    PushSubscriptionsDelete = 'pushSubscriptionsDelete',

    UserAliasesList = 'userAliasesList',
    UserAliasesCreate = 'userAliasesCreate',
    UserAliasesDelete = 'userAliasesDelete',

    ActorRead = 'actorRead',
    HealthRead = 'healthRead',

    ArchivesList = 'archivesList',
    ArchivesCreate = 'archivesCreate',

    UserSettingsList = 'userSettingsList',
    UserSettingsRead = 'userSettingsRead',
    UserSettingsSet = 'userSettingsSet',
    UserSettingsDelete =  'userSettingsDelete',

    FollowImportsList = 'followImportsList',
    FollowImportsUpload = 'followImportsUpload',

    ArticlesList = 'articlesList',
    ArticlesRead = 'articlesRead',
    ArticlesCreate = 'articlesCreate',
    ArticlesUpdate = 'articlesUpdate',
    ArticlesDelete = 'articlesDelete',
    ArticlesDismiss = 'articlesDismiss',

    BusinessCardsRead = 'businessCardsRead',
    BusinessCardsCreate = 'businessCardsCreate',
    BusinessCardsUpdate = 'businessCardsUpdate',
    BusinessCardsAvatar = 'businessCardsAvatar',
    
    SharedBusinessCardList = 'sharedBusinessCardList',
    SharedBusinessCardRead = 'sharedBusinessCardRead',
    SharedBusinessCardCreate = 'sharedBusinessCardCreate',
    SharedBusinessCardUpdate = 'sharedBusinessCardUpdate',
    SharedBusinessCardDelete = 'sharedBusinessCardDelete',
    SharedBusinessCardMessage = 'sharedBusinessCardMessage',
    SharedBusinessCardRevoke = 'sharedBusinessCardRevoke',
    SharedBusinessCardUnrevoke = 'sharedBusinessCardUnrevoke',
    SharedBusinessCardReadByThirdParty = 'sharedBusinessCardReadByThirdParty',
    SharedBusinessCardUpdateByThirdParty = 'sharedBusinessCardUpdateByThirdParty',
    SharedBusinessCardMessageByThirdParty = 'sharedBusinessCardMessageByThirdParty',

    QuickCaptchaGenerate = 'quickCaptchaGenerate'
}