export enum EventType {

    Unknown = 'unknown',

    AccountLogin = 'accountLogin',
    AccountRefresh = 'accountRefresh',
    AccountConfirm = 'accountConfirm',
    AccountChangeEmail = 'accountChangeEmail',
    AccountChangePassword = 'accountChangePassword',
    AccountForgotToken = 'accountForgotToken',
    AccountForgotConfirm = 'accountForgotConfirm',
    AccountRevoke = 'accountRevoke',
    AccountGetTwoFactorToken = 'accountGetTwoFactorToken',
    AccountEnableTwoFactorAuthentication = 'accountEnableTwoFactorAuthentication',
    AccountDisableTwoFactorAuthentication = 'accountDisableTwoFactorAuthentication',
    
    AuthClientsCreate = 'authClientsCreate',
    AuthClientsList = 'authClientsList',
    AuthClientsRead = 'authClientsRead',
    AuthClientsUpdate = 'authClientsUpdate',
    AuthClientsDelete = 'authClientsDelete',
    
    RegisterNewUser = 'registerNewUser',
    RegisterUserName = 'registerUserName',
    RegisterEmail = 'registerEmail',
    
    RolesCreate = 'rolesCreate',
    RolesList = 'rolesList',
    RolesRead = 'rolesRead',
    RolesUpdate = 'rolesUpdate',
    RolesDelete = 'rolesDelete',
    
    UsersList = 'usersList',
    UsersRead = 'usersRead',
    UsersUpdate = 'usersUpdate',
    UsersDelete = 'usersDelete',
    UsersFollow = 'usersFollow',
    UsersUnfollow = 'usersUnfollow',
    UsersFollowers = 'usersFollowers',
    UsersFollowing = 'usersFollowing',
    UsersMute = 'usersMute',
    UsersUnmute = 'usersUnmute',
    UsersEnable = 'usersEnable',
    UsersDisable = 'usersDisable',
    UserRolesConnect = 'userRolesConnect',
    UserRolesDisconnect = 'userRolesDisconnect',
    UserApprove = 'userApprove',
    UserReject = 'userReject',
    UsersStatuses = 'usersStatuses',
    
    AvatarUpdate = 'avatarUpdate',
    AvatarDelete = 'avatarDelete',

    HeaderUpdate = 'headerUpdate',
    HeaderDelete = 'headerDelete',
    
    AttachmentsCreate = 'attachmentsCreate',
    AttachmentsUpdate = 'attachmentsUpdate',
    AttachmentsDelete = 'attachmentsDelete',
    
    SettingsList = 'settingsList',
    SettingsPublic = 'settingsPublic',
    SettingsUpdate = 'settingsUpdate',
    
    ActivityPubRead = 'activityPubRead',
    ActivityPubInbox = 'activityPubInbox',
    ActivityPubOutbox = 'activityPubOutbox',
    ActivityPubFollowing = 'activityPubFollowing',
    ActivityPubFollowers = 'activityPubFollowers',
    ActivityPubLiked = 'activityPubLiked',
    ActivityPubSharedInbox = 'activityPubSharedInbox',
    ActivityPubStatus = 'activityPubStatus',
    
    Webfinger = 'webfinger',
    Nodeinfo = 'nodeinfo',
    HostMeta = 'hostMeta',
    Instance = 'instance',
    
    CountriesList = 'countriesList',
    LocationsList = 'locationsList',
    LocationsRead = 'locationsRead',

    CategoriesList = 'categoriesList',
    
    StatusesList = 'statusesList',
    StatusesCreate = 'statusesCreate',
    StatusesRead = 'statusesRead',
    StatusesUpdate = 'statusesUpdate',
    StatusesDelete = 'statusesDelete',
    StatusesReblog = 'statusesReblog',
    StatusesUnreblog = 'statusesUnreblog',
    StatusesFavourite = 'statusesFavourite',
    StatusesUnfavourite = 'statusesUnfavourite',
    StatusesBookmark = 'statusesBookmark',
    StatusesUnbookmark = 'statusesUnbookmark',
    StatusesFeature = 'statusesFeature',
    StatusesUnfeature = 'statusesUnfeature',
    StatusesContext = 'statusesContext',
    StatusesReblogged = 'statusesReblogged',
    StatusesFavourited = 'statusesFavourited',
    
    TimelinesPublic = 'timelinesPublic',
    TimelinesCategories = 'timelinesCategories',
    TimelinesHashtags = 'timelinesHashtags',
    TimelinesFeatured = 'timelinesFeatured',
    TimelinesHome = 'timelinesHome',
    
    FollowRequestList = 'followRequestList',
    FollowRequestApprove = 'followRequestApprove',
    FollowRequestReject = 'followRequestReject',
    
    NotificationsList = 'notificationsList',
    NotificationsCount = 'notificationsCount',
    NotificationsUpdateMarker = 'notificationsUpdateMarker',

    Relationships = 'relationships',
    Search = 'search',

    InvitationList = 'invitationList',
    InvitationGenerate = 'invitationGenerate',
    InvitationDelete = 'invitationDelete',

    ReportsCreate = 'reportsCreate',
    ReportsList = 'reportsList',
    ReportsClose = 'reportsClose',
    ReportsRestore = 'reportsRestore',

    TrendingStatuses = 'trendingStatuses',
    TrendingUsers = 'trendingUsers',
    TrendingHashtags = 'trendingHashtags'
}