export enum EventType {

    Unknown = 'unknown',

    AccountLogin = 'accountLogin',
    AccountLogout = 'accountLogout',
    AccountRefresh = 'accountRefresh',
    AccountConfirm = 'accountConfirm',
    AccountIsEmailVerified = 'accountIsEmailVerified',
    AccountChangeEmail = 'accountChangeEmail',
    AccountChangePassword = 'accountChangePassword',
    AccountForgotToken = 'accountForgotToken',
    AccountForgotConfirm = 'accountForgotConfirm',
    AccountRevoke = 'accountRevoke',
    AccountGetTwoFactorToken = 'accountGetTwoFactorToken',
    AccountEnableTwoFactorAuthentication = 'accountEnableTwoFactorAuthentication',
    AccountDisableTwoFactorAuthentication = 'accountDisableTwoFactorAuthentication',
    AccountEnableSupporterFlag = 'accountEnableSupporterFlag',
    AccountDisableSupportedFlag = 'accountDisableSupportedFlag',
    
    AuthClientsCreate = 'authClientsCreate',
    AuthClientsList = 'authClientsList',
    AuthClientsRead = 'authClientsRead',
    AuthClientsUpdate = 'authClientsUpdate',
    AuthClientsDelete = 'authClientsDelete',

    AuthDynamicClientsCreate = `authDynamicClientsCreate`,
    
    OAuthAuthenticate = 'oAuthAuthenticate',
    OAuthAuthenticateCallback = 'oAuthAuthenticateCallback',
    OAuthToken = 'oAuthToken',

    RegisterNewUser = 'registerNewUser',
    RegisterUserName = 'registerUserName',
    RegisterEmail = 'registerEmail',
    
    RolesCreate = 'rolesCreate',
    RolesList = 'rolesList',
    RolesRead = 'rolesRead',
    RolesUpdate = 'rolesUpdate',
    RolesDelete = 'rolesDelete',
    
    UsersList = 'usersList',
    UsersRead = 'usersRead',
    UsersUpdate = 'usersUpdate',
    UsersDelete = 'usersDelete',
    UsersFollow = 'usersFollow',
    UsersUnfollow = 'usersUnfollow',
    UsersFollowers = 'usersFollowers',
    UsersFollowing = 'usersFollowing',
    UsersMute = 'usersMute',
    UsersUnmute = 'usersUnmute',
    UsersEnable = 'usersEnable',
    UsersDisable = 'usersDisable',
    UsersBlock = 'usersBlock',
    UsersUnblock = 'usersUnblock',
    UsersSupporter = 'usersSupporter',
    UsersNotSupporter = 'usersNotSupporter',
    UserRolesConnect = 'userRolesConnect',
    UserRolesDisconnect = 'userRolesDisconnect',
    UserApprove = 'userApprove',
    UserReject = 'userReject',
    UserFeature = 'userFeature',
    UserUnfeature = 'userUnfeature',
    UsersStatuses = 'usersStatuses',
    UsersRemoveOneTimePassword = 'usersRemoveOneTimePassword',
    
    AvatarUpdate = 'avatarUpdate',
    AvatarDelete = 'avatarDelete',

    HeaderUpdate = 'headerUpdate',
    HeaderDelete = 'headerDelete',
    
    AttachmentsCreate = 'attachmentsCreate',
    AttachmentsHdrCreate = 'attachmentsHdrCreate',
    AttachmentsHdrDelete = 'attachmentsHdrDelete',
    AttachmentsUpdate = 'attachmentsUpdate',
    AttachmentsDelete = 'attachmentsDelete',
    AttachmentsDescribe = 'attachmentsDescribe',
    AttachmentsHashtags = 'attachmentsHashtags',
    
    SettingsList = 'settingsList',
    SettingsPublic = 'settingsPublic',
    SettingsUpdate = 'settingsUpdate',
    
    ActivityPubRead = 'activityPubRead',
    ActivityPubFeatured = 'activityPubFeatured',
    ActivityPubInbox = 'activityPubInbox',
    ActivityPubOutbox = 'activityPubOutbox',
    ActivityPubFollowing = 'activityPubFollowing',
    ActivityPubFollowers = 'activityPubFollowers',
    ActivityPubLiked = 'activityPubLiked',
    ActivityPubSharedInbox = 'activityPubSharedInbox',
    ActivityPubStatus = 'activityPubStatus',
    
    Webfinger = 'webfinger',
    Nodeinfo = 'nodeinfo',
    HostMeta = 'hostMeta',
    Instance = 'instance',
    
    CountriesList = 'countriesList',
    LocationsList = 'locationsList',
    LocationsRead = 'locationsRead',

    CategoriesList = 'categoriesList',
    CategoriesCreate = 'categoriesCreate',
    CategoriesUpdate = 'categoriesUpdate',
    CategoriesDelete = 'categoriesDelete',
    CategoriesEnable = 'categoriesEnable',
    CategoriesDisable = 'categoriesDisable',
    
    LicensesList = 'licensesList',
    LicensesCreate = 'licensesCreate',
    LicensesUpdate = 'licensesUpdate',
    LicensesDelete = 'licensesDelete',

    HomeCardsList = 'homeCardsList',
    HomeCardsCachedList = 'homeCardsCachedList',
    HomeCardsCreate = 'homeCardsCreate',
    HomeCardsUpdate = 'homeCardsUpdate',
    HomeCardsDelete = 'homeCardsDelete',

    StatusesList = 'statusesList',
    StatusesCreate = 'statusesCreate',
    StatusesRead = 'statusesRead',
    StatusesUpdate = 'statusesUpdate',
    StatusesDelete = 'statusesDelete',
    StatusesUnlist = 'statusesUnlist',
    StatusesApplyContentWarning = 'statusesApplyContentWarning',
    StatusesReblog = 'statusesReblog',
    StatusesUnreblog = 'statusesUnreblog',
    StatusesFavourite = 'statusesFavourite',
    StatusesUnfavourite = 'statusesUnfavourite',
    StatusesBookmark = 'statusesBookmark',
    StatusesUnbookmark = 'statusesUnbookmark',
    StatusesPin = 'statusesPin',
    StatusesUnpin = 'statusesUnpin',
    StatusesFeature = 'statusesFeature',
    StatusesUnfeature = 'statusesUnfeature',
    StatusesContext = 'statusesContext',
    StatusesHistory = 'statusesHistory',
    StatusesReblogged = 'statusesReblogged',
    StatusesFavourited = 'statusesFavourited',
    StatusesEvents = 'statusesEvents',
    StatusesEventItems = 'statusesEventItems',
    
    TimelinesPublic = 'timelinesPublic',
    TimelinesCategories = 'timelinesCategories',
    TimelinesHashtags = 'timelinesHashtags',
    TimelinesFeaturedStatuses = 'timelinesFeaturedStatuses',
    TimelinesFeaturedUsers = 'timelinesFeaturedUsers',
    TimelinesHome = 'timelinesHome',
    
    FollowRequestList = 'followRequestList',
    FollowRequestApprove = 'followRequestApprove',
    FollowRequestReject = 'followRequestReject',
    
    NotificationsList = 'notificationsList',
    NotificationsCount = 'notificationsCount',
    NotificationsUpdateMarker = 'notificationsUpdateMarker',

    Relationships = 'relationships',
    Search = 'search',

    InvitationList = 'invitationList',
    InvitationGenerate = 'invitationGenerate',
    InvitationDelete = 'invitationDelete',

    ReportsCreate = 'reportsCreate',
    ReportsList = 'reportsList',
    ReportsClose = 'reportsClose',
    ReportsRestore = 'reportsRestore',
    ReportsSend = 'reportsSend',

    TrendingStatuses = 'trendingStatuses',
    TrendingUsers = 'trendingUsers',
    TrendingHashtags = 'trendingHashtags',

    BookmarksList = 'bookmarksList',
    FavouritesList = 'favouritesList',

    InstanceBlockedDomainsList = 'instanceBlockedDomainsList',
    InstanceBlockedDomainsRead = 'instanceBlockedDomainsRead',
    InstanceBlockedDomainsCreate = 'instanceBlockedDomainsCreate',
    InstanceBlockedDomainsUpdate = 'instanceBlockedDomainsUpdate',
    InstanceBlockedDomainsDelete = 'instanceBlockedDomainsDelete',

    UserBlockedUsersList = 'userBlockedUsersList',

    UserBlockedDomainsList = 'userBlockedDomainsList',
    UserBlockedDomainsRead = 'userBlockedDomainsRead',
    UserBlockedDomainsCreate = 'userBlockedDomainsCreate',
    UserBlockedDomainsUpdate = 'userBlockedDomainsUpdate',
    UserBlockedDomainsDelete = 'userBlockedDomainsDelete',

    UserMutesList = 'userMutesList',

    PushSubscriptionsList = 'pushSubscriptionsList',
    PushSubscriptionsCreate = 'pushSubscriptionsCreate',
    PushSubscriptionsUpdate = 'pushSubscriptionsUpdate',
    PushSubscriptionsDelete = 'pushSubscriptionsDelete',

    RulesList = 'rulesList',
    RulesCreate = 'rulesCreate',
    RulesUpdate = 'rulesUpdate',
    RulesDelete = 'rulesDelete',

    UserAliasesList = 'userAliasesList',
    UserAliasesCreate = 'userAliasesCreate',
    UserAliasesDelete = 'userAliasesDelete',

    ActorRead = 'actorRead',
    HealthRead = 'healthRead',

    ErrorList = 'errorList',
    ErrorRead = 'errorRead',
    ErrorCreate = 'errorCreate',
    ErrorDelete = 'errorDelete',

    ArchivesList = 'archivesList',
    ArchivesCreate = 'archivesCreate',

    ExportsFollowing = 'exportsFollowing',
    ExportsBookmarks = 'exportsBookmarks',

    UserSettingsList = 'userSettingsList',
    UserSettingsRead = 'userSettingsRead',
    UserSettingsSet = 'userSettingsSet',
    UserSettingsDelete =  'userSettingsDelete',

    RssUser = 'rssUser',
    RssLocal = 'rssLocal',
    RssGlobal = 'rssGlobal',
    RssTrending = 'rssTrending',
    RssFeatured = 'rssFeatured',
    RssCategories = 'rssCategories',
    RssHashtags = 'rssHashtags',

    AtomUser = 'atomUser',
    AtomLocal = 'atomLocal',
    AtomGlobal = 'atomGlobal',
    AtomTrending = 'atomTrending',
    AtomFeatured = 'atomFeatured',
    AtomCategories = 'atomCategories',
    AtomHashtags = 'atomHashtags',

    FollowImportsList = 'followImportsList',
    FollowImportsUpload = 'followImportsUpload',

    ArticlesList = 'articlesList',
    ArticlesRead = 'articlesRead',
    ArticlesCreate = 'articlesCreate',
    ArticlesUpdate = 'articlesUpdate',
    ArticlesDelete = 'articlesDelete',
    ArticlesFileUpload = 'articlesFileUpload',
    ArticlesFileDelete = 'articlesFileDelete',
    ArticlesMainFile = 'articlesMainFile',
    ArticlesDismiss = 'articlesDismiss',

    BusinessCardsRead = 'businessCardsRead',
    BusinessCardsCreate = 'businessCardsCreate',
    BusinessCardsUpdate = 'businessCardsUpdate',
    BusinessCardsAvatar = 'businessCardsAvatar',
    
    SharedBusinessCardList = 'sharedBusinessCardList',
    SharedBusinessCardRead = 'sharedBusinessCardRead',
    SharedBusinessCardCreate = 'sharedBusinessCardCreate',
    SharedBusinessCardUpdate = 'sharedBusinessCardUpdate',
    SharedBusinessCardDelete = 'sharedBusinessCardDelete',
    SharedBusinessCardMessage = 'sharedBusinessCardMessage',
    SharedBusinessCardRevoke = 'sharedBusinessCardRevoke',
    SharedBusinessCardUnrevoke = 'sharedBusinessCardUnrevoke',
    SharedBusinessCardReadByThirdParty = 'sharedBusinessCardReadByThirdParty',
    SharedBusinessCardUpdateByThirdParty = 'sharedBusinessCardUpdateByThirdParty',
    SharedBusinessCardMessageByThirdParty = 'sharedBusinessCardMessageByThirdParty',

    QuickCaptchaGenerate = 'quickCaptchaGenerate',
    StatusActivityPubEventsList = 'statusActivityPubEventsList',
    StatusActivityPubEventsItems = 'statusActivityPubEventsItems'
}
