image: node:20

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://127.0.0.1:2375"

stages:
  - test 
  - image

test build:
  stage: test
  before_script:
    - npm install --force
  script:
    - npm run lint
    - npm run build
  rules:
    - when: never

build image:
  image: docker:25-dind
  services:
    - name: docker:25-dind
  stage: image
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  script:
    - echo "IMAGE_TAG=${IMAGE_TAG}"
    - echo "${CI_JOB_TOKEN}" | docker login --username="gitlab-ci-token" --password-stdin "${CI_REGISTRY_IMAGE}"
    - docker build -t "${IMAGE_TAG}" .
    - docker push "${IMAGE_TAG}"
#  rules:
#    - when: manual

