image: node:20

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - test 
  - image

test build:
  stage: test
  before_script:
    - npm install --force
  script:
    - npm run lint
    - npm run build
  rules:
    - when: never

build image:
  image: docker:24-dind
  services:
    - name: docker:24-dind
      variables:
        HEALTHCHECK_TCP_PORT: "2376"
  before_script:
    - docker info
  stage: image
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  script:
    - echo "IMAGE_TAG=${IMAGE_TAG}"
    - echo "${CI_JOB_TOKEN}" | docker login --username="gitlab-ci-token" --password-stdin "${CI_REGISTRY_IMAGE}"
    - docker build -t "${IMAGE_TAG}" .
    - docker push "${IMAGE_TAG}"
#  rules:
#    - when: manual

