image: node:20

# And to cache them as well.
cache:
  paths:
    - node_modules/

stages:
  - test 
  - image

build:
  stage: test
  before_script:
    - npm install --force
  script:
    - npm run lint
    - npm run build
