image: node:20

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://127.0.0.1:2375"

# And to cache them as well.
cache:
  paths:
    - node_modules/

stages:
  - test 
  - image

test build:
  stage: test
  before_script:
    - npm install --force
  script:
    - npm run lint
    - npm run build

build image:
  image: docker:20-dind
  services:
    - name: docker:20-dind
      command: ["--tls=false"]
  stage: image
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  script:
    - echo "IMAGE_TAG=${IMAGE_TAG}"
    - echo "${CI_JOB_TOKEN}" | docker login --username="gitlab-ci-token" --password-stdin "${CI_REGISTRY_IMAGE}"
    - docker build -t "${IMAGE_TAG}" .
    - docker push "${IMAGE_TAG}"
